FROM php:7.4.11-apache
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
COPY start-apache /usr/local/bin
RUN a2enmod rewrite
RUN chown -R www-data:www-data /var/www/html
COPY source/ /var/www/html/
CMD ["start-apache"]
